language: ruby
cache: bundler
before_install:
- gem update --system
- gem install bundler
matrix:
  include:
  - rvm: ruby-head
    gemfile: gemfiles/Gemfile.ci
    script: bundle exec rake ci
  - rvm: rbx-3.14
    gemfile: Gemfile
    script: bundle exec rake test
  - rvm: 2.2
    gemfile: gemfiles/Gemfile.doc
    script: bundle exec rake yard:deploy
    env: DOCS=true
sudo: false
env:
  global:
  - secure: jYC8ApWzl2StVQ2MgeJj7SMC5K2pBUDTjSnf+Z7/5s1qByHBVTLjh8iIxJKv+nFv33Mz9wt35qAQH/IqXUgXpCmER9XSrM54uz8ei8ewiDwsaJLtBkBoYaJ7NZ/EKbT7vZL0HiQHtc9o1hKX4yqHh8RdAKArwG09HWS6DS4OT1YsJzm50JqbeDLh6uQbcBqRN2phpA97K1eU16YGlQ6Ct4Hwh7tzQ1mfkMmJt2/bzqR9cdzu4CEkm7QMUyirMNz4dlPC2b1fH/MsizenaDbhDgf6jhZRbv0E4X5URq7HqIGBzTbIOcJfz6D6GNPhV8DQlUEVIzsg4lMwxOVyIbuUzIAuSSqUFBive+TWB3zcya4SP/I3Tmic+FOR3pazq4+Dpl1xVRMb717WMXEPFukmuliiMrIXakRDAOT7uqgRDKm1diuFVTswqJ2NXOOd729dQwke70+pA9U8g8eVlS1hYU1HqoEAaNox5K2Dd6FpeVZ/Dsmcg1WU9XTiOO9feEumXlVL3MsQo2Uc0GJ9eSDWKS6o1U1J77gzqjW6HMzV2VDwzvsgLJ4RYbLl/zUmuNehifG21mj8eoJe0iUnGHIJ6cauuKZEa+UnERwoRC3pkoMPTQNu618ZxFd/iyMHBG3HCr+u1J95ShhAY7+oRHi3RXWzY23VZZZln7m1qYSN1mA=
  - secure: 272+CcXqxoytsna8B2KSPgYG7XGoAkQ9X37hVd8x2SEpizkO4/YAvW80WBTNfXqBWjyNUtO9tuLMwlJo9N6ArQQRAqCeFfdHjSFMxkjKosSeI+YXH848NDyWYFXoGRULFBl6JwoMF+RDW6oqyv68htea9lp7iA9UbI94UtV1OqRVkEPMJGA9Al+5UuQdSrV7Sdt2pSSya+yZmq3w3ivi7IZtZAiGevcVyNgnbNhHCeUfwufGOi7WiwxHI46hoUF3QpsfZJHki71VedEkPVrVgkYjvlgPT04WJeQyM/3amJlb5VZ34h+HXrl40+pqqoVYAJcAMrca+vHC4Don6nleDqNpA3sqi26H6ZyDf1hJQYWG3YeuNAtjXRtMd0Aq0tkH0sABD4FNo4tOt1RHCjsEN2ZnG4WKudEqBRMqru2YNU675NIi0cJDnjAfqPXxlxWql+V4FBVhO1oe53pm3GxAr+b9Tr6beMH8RkQB0prYe8S56DsmWJZ1HBqgWpP5U42XK+0KbLpjChlgBOBkg0ZdcVQtx+YJ7RClnwh4mTyXpddPMTkiluOaJNZUWUx3srqu4vJy7bMdjNPQRgcgJEVNOhKYjPL+MexvUxSxmlNe/h24j3D0Gm5DpCR5MjyNnecSYmFb3jDbmutKMzkK54o+S+Pw7ZMkpY/WuoRBkppozgo=
  - secure: PFuPj0wDHm4rrGpe2H+jWOaY8RY4JOjEypA/gbkkL7edNn5JXhJPue2L9mk1JfSTmBpramhTmCHUogFbPKHjwv22ODhm2VfsuizLOkVw9+u+UfV8aQAa91qhCSTkEIbjg/zHEfcW0EHbTxDq6ln7XasRdEIIKOxU9GClTC1nZvSlqEGRDM5MoULK0s+amjuirVKMiR85XZj0SPLZt97AV7rQTZMiKCeSo+lEG7JQzaJmbD+T5aao6mtHVGrR4Ezg+HCMwPhU1Bt3/XUYUg0wL6zBd66gIOUdgQjrLNaEc25KjuTsfQuDv9poZ0LJB7fGQVayfq/jK9/dmWk5gAKUDGt5z3R50p3uTW6wYGtHn5UCQohEeYLIkfnLBvioamK9Bx36+fgKymD+WZ8RQk0vb4o5oxDLtpP6d1VzxJ3jy8sYpJnnjnJdZGJSv4vrtPHBU7wYAwON7egz57q82fr9suUTWDkLQi6aP3vv/DeaqZjhWFn2JP/4suLjfwRPFVxao89xG4khlUyrKYqbVt2iBfte5G8ltxctqtptvGiQIbXyOiISoVjiCRG8GOChmjbr2cVzY7a72DmnEyhLmMdv09Qq12LjcLEvl25jpwrNNFyScowQVUrhbaoh13khpm6zRBf69DMySsITuB+e3zyj+LMlEGQFDL9toWVdDYXc5/g=
